### ISSUE TITLE
Update jquery dependency

### ISSUE THREAD

**Issue by ameerthehacker** [ameerthehacker/jquery-simple-validator#10]
## Description

* Update the jquery dependency in package.json to the latest version
* Run the tests to make sure nothing is breaking

## Useful links

The latest version of jquery can be found here https://www.npmjs.com/package/jquery

**Comment by poojakp94** [comment]
I would like to work on this.

**Comment by ameerthehacker** [comment]
please goahead

**Comment by ameerthehacker** [comment]
closing this as a PR was made and merged
