### ISSUE TITLE
Replace npm with yarn

### ISSUE THREAD

**Issue by ameerthehacker** [ameerthehacker/jquery-simple-validator#14]
## Description

* Install yarn in your local system
* Remove the package-lock.json
* Run yarn install
* Commit with the file yarn.lock which will be automatically generated
* Update the README by replacing the **npm** commands with **yarn**

**Comment by nicmeriano** [comment]
I can do this!

**Comment by ameerthehacker** [comment]
Please goahead

**Comment by ameerthehacker** [comment]
closing this issue as a PR was made and merged
