### ISSUE TITLE
Add prettier to auto-format the code whenever someone commits changes

### ISSUE THREAD

**Issue by ameerthehacker** [ameerthehacker/jquery-simple-validator#9]
## Description

* Add **prettier-quick**, **husky** as a dev dependency and use husky to automatically format staged files.
* Add a .prettierrc file to specify the code formatting settings
* Add a .prettierignore file to ignore unwanted directories like node_modules

## Useful links

The complete process is available here https://prettier.io/docs/en/precommit.html

**Comment by PragunSaini** [comment]
I'd like to take up this one too.

**Comment by ameerthehacker** [comment]
Please goahead
